### ISSUE TITLE
I think the static first page is a bit confusing

### ISSUE THREAD

**Issue by esaliya** [DSC-SPIDAL/WebPViz#31]
Not really an issue, but more of a usability improvement.

The first page WebPViz gives an introduction and has a static image. I think this is a bit confusing.

It'll be better if content of this page is moved to something like "About" page. Then for the first page we can actually show a sample plot that one can rotate and do all the fancy things and give the option to sign in, so  a user can register/sign-in and use this to visualize his/her own plot

**Comment by supunkamburugamuve** [comment]
We have added information to first page and it serves as an information page
