### ISSUE TITLE
The plot should rotate around the center of its points

### ISSUE THREAD

**Issue by esaliya** [DSC-SPIDAL/WebPViz#32]
or better if user can pick center to rotate around. This is not urgent, but we used this a lot in desktop version

**Comment by pulasthi** [comment]
You can use the pan function (Mouse move + right mouse button) to change the center location. I think we can use that for now and add this later as an UX improvement

**Comment by esaliya** [comment]
I think what I meant is a bit different from this. See plot
http://spidal-gw.dsc.soic.indiana.edu/plot?rid=0&tid=1163312502. When you
use mouse to rotate (Mouse move + left click) it seems to rotate around the
edge of the points sphere.

I think the way to fix this would be to keep the center point computed and
set the rotation around that.

On Mon, Nov 9, 2015 at 1:21 PM, pulasthi supun notifications@github.com
wrote:

> You can use the pan function (Mouse move + right mouse button) to change
> the center location. I think we can use that for now and add this later as
> an UX improvement
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/32#issuecomment-155145914.

## 

Saliya Ekanayake
Ph.D. Candidate | Research Assistant
School of Informatics and Computing | Digital Science Center
Indiana University, Bloomington
Cell 812-391-4914
http://saliya.org

**Comment by supunkamburugamuve** [comment]
This is fixed now
