### ISSUE TITLE
There should be a function to reset the orientation to the original

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/WebPViz#4]

**Comment by foxsden** [comment]
Can we get a version to demo at SC15?

On Mon, Nov 2, 2015 at 10:29 AM, Supun Kamburugamuve <
notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/4.

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org

**Comment by foxsden** [comment]
Yes, we should able to demo in SC15. I think we are in a working state now.
Fixing the corner cases.

Thanks,
Supun..

On Mon, Nov 2, 2015 at 10:58 AM, Geoffrey Fox gcfexchange@gmail.com wrote:

> Can we get a version to demo at SC15?
> 
> On Mon, Nov 2, 2015 at 10:29 AM, Supun Kamburugamuve <
> notifications@github.com> wrote:
> 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/DSC-SPIDAL/WebPViz/issues/4.
> 
> ## 
> 
> :
> : Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
> http://www.infomall.org

## 

Supun Kamburugamuva
Member, Apache Software Foundation; http://www.apache.org
E-mail: supun06@gmail.com;  Mobile: +1 812 369 6762
Blog: http://supunk.blogspot.com

**Comment by pulasthi** [comment]
Reset button added https://github.com/DSC-SPIDAL/WebPViz/commit/85ce145fc02c4d4bd11fb4fac62fc93a15516168
