### ISSUE TITLE
Add support for phylogenetic trees to be viewed

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/WebPViz#49]

**Comment by foxsden** [comment]
How long will it take to get WebPlotviz ~complete and with sample of good
initial data?

On Sat, Dec 12, 2015 at 10:04 PM, Supun Kamburugamuve <
notifications@github.com> wrote:

> Closed #49 https://github.com/DSC-SPIDAL/WebPViz/issues/49.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/49#event-490257253.

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org

**Comment by supunkamburugamuve** [comment]
I think by end of day today I should be able to finish the saving of
cluster colors. This is the major thing left. Will upload the new results
within few hours as well.

Thanks,
Supun..

**Comment by foxsden** [comment]
What is our preferred format for new users. I assume it's not .pviz?

**Comment by supunkamburugamuve** [comment]
Right now it is pviz. We can support Json as well. Personally I feel xml is
more clear for a user but I may be wrong.

Thanks,
Supun...

**Comment by foxsden** [comment]
We need a clean specification with good defaukts and a nice upload interface

On Sun, Dec 13, 2015 at 8:36 PM, Supun Kamburugamuve <
notifications@github.com> wrote:

> Right now it is pviz. We can support Json as well. Personally I feel xml is
> more clear for a user but I may be wrong.
> 
> Thanks,
> Supun...
> 
> On Sun, Dec 13, 2015, 20:32 Geoffrey Fox notifications@github.com wrote:
> 
> > What is our preferred format for new users. I assume it's not .pviz?
> > On Dec 14, 2015 6:47 AM, "Supun Kamburugamuve" <notifications@github.com
> > 
> > wrote:
> > 
> > > I think by end of day today I should be able to finish the saving of
> > > cluster colors. This is the major thing left. Will upload the new
> > > results
> > > within few hours as well.
> > > 
> > > Thanks,
> > > Supun..
> > > 
> > > On Sun, Dec 13, 2015, 20:01 Geoffrey Fox notifications@github.com
> > > wrote:
> > > 
> > > > How long will it take to get WebPlotviz ~complete and with sample of
> > > > good
> > > > initial data?
> > > > 
> > > > On Sat, Dec 12, 2015 at 10:04 PM, Supun Kamburugamuve <
> > > > notifications@github.com> wrote:
> > > > 
> > > > > Closed #49 https://github.com/DSC-SPIDAL/WebPViz/issues/49.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/DSC-SPIDAL/WebPViz/issues/49#event-490257253.
> > > > 
> > > > ## 
> > > > 
> > > > :
> > > > : Geoffrey Fox gcf@indiana.edu Phones Cell 812-219-4643 Lab
> > > > 8128567977
> > > > http://www.infomall.org
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/DSC-SPIDAL/WebPViz/issues/49#issuecomment-164316720
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/DSC-SPIDAL/WebPViz/issues/49#issuecomment-164317877
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/DSC-SPIDAL/WebPViz/issues/49#issuecomment-164318984
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/49#issuecomment-164319525.

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org
