### ISSUE TITLE
An option to reset a plot is necessary

### ISSUE THREAD

**Issue by esaliya** [DSC-SPIDAL/WebPViz#50]
This is useful because I found after rotating and changing the center it sometimes become hard to correctly look at a plot, so an option to reset (like reload, but not necessarily bringing data from back end).

**Comment by pulasthi** [comment]
This is already available. I changed the icon with https://github.com/DSC-SPIDAL/WebPViz/commit/91104e31adcb3a2e9471557b7e13e4762265110e to make it more clear. the left most button resets the view to default position.
