### ISSUE TITLE
Ability to save plots after changes are done in the front end

### ISSUE THREAD

**Issue by pulasthi** [DSC-SPIDAL/WebPViz#56]

**Comment by supunkamburugamuve** [comment]
Now we can save the rotations and zoom level. Need to save the cilors

**Comment by supunkamburugamuve** [comment]
Added functionality to save colors assigned to clusters

**Comment by foxsden** [comment]
Do you save the the 3 size measures
speed
point size
glyph size

That's needed for casual user

On Mon, Dec 14, 2015 at 2:04 PM, Supun Kamburugamuve <
notifications@github.com> wrote:

> Closed #56 https://github.com/DSC-SPIDAL/WebPViz/issues/56.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/56#event-491349891.

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org
