### ISSUE TITLE
The setting panel is consuming so much memory

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/WebPViz#67]
When a time series is played with settings panel it consumes lot of memory.

The reason is
1. It generates the setting panel from scratch for each frame
2. Then registers events etc to these generated HTML using color pickers etc
3. When new HTML is added, the previous event handlers are still there. So the previous HTML doesn't get garbage colllected

Solution

Generate the settings panel once and update it when the frames change without generating it again and again.

**Comment by pulasthi** [comment]
This is now added
