### ISSUE TITLE
Rotate only around an given axis when pressing a key

### ISSUE THREAD

**Issue by supunkamburugamuve** [DSC-SPIDAL/WebPViz#75]
If we press a key and rotate, it should rotate only around 1 axis

For example press x and rotate around Alt + X and it should rotate only around X

**Comment by pulasthi** [comment]
Feature Added to the master with d23bbdb6bdeeb8d3c3954ddb1ce77eee5bd941c5.

Rotation works with the following commands

Shift + x -> rotation around x axis
Shift + y -> rotation around y axis
Shift + z -> rotation around z axis
