### ISSUE TITLE
Allow support for 2D plots 

### ISSUE THREAD

**Issue by pulasthi** [DSC-SPIDAL/WebPViz#79]
Add the ability to add 2D plots that it does not rotate around the z axis

**Comment by foxsden** [comment]
rotate around the z axis
should be
rotate the z axis

On Mon, Jun 6, 2016 at 4:43 PM, pulasthi supun notifications@github.com
wrote:

> Add the ability to add 2D plots that it does not rotate around the z axis
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/79, or mute the thread
> https://github.com/notifications/unsubscribe/AGPrF_ZM0YySoDbfMpWfdwb9gnaa8UXLks5qJIZ-gaJpZM4IvS8_
> .

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org

**Comment by pulasthi** [comment]
Support added for 2D plots with 55633ea2280b3e378c8aec2fa4cca247cd2daec0

Notes: 
Users can switch between 2D and 3D mode by pressing SHIFT + 2 and SHIFT + 3 keys respectively. Once in 2D mode pan option will work with left mouse button pressed ( rather than right mouse button that used in normal mode. In normal more left  mouse button pressed is used for rotation ).
