### ISSUE TITLE
Add some sample pviz files or an archive to the git repo for testing

### ISSUE THREAD

**Issue by milinda** [DSC-SPIDAL/WebPViz#9]

**Comment by supunkamburugamuve** [comment]
Added one sample to samples folder

**Comment by foxsden** [comment]
Can you give me a demo tomorrow or is that premature?

On Tue, Nov 3, 2015 at 3:31 PM, Supun Kamburugamuve <
notifications@github.com> wrote:

> Added one sample to samples folder
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/9#issuecomment-153477972.

## 

:
: Geoffrey Fox  gcf@indiana.edu Phones Cell 812-219-4643  Lab 8128567977
http://www.infomall.org

**Comment by supunkamburugamuve** [comment]
We have some issues with performance when loading large number of PViz
files. We can give a demo with the functionality as it is now.

Thanks,
SUpun..

On Tue, Nov 3, 2015 at 3:37 PM, Geoffrey Fox notifications@github.com
wrote:

> Can you give me a demo tomorrow or is that premature?
> 
> On Tue, Nov 3, 2015 at 3:31 PM, Supun Kamburugamuve <
> notifications@github.com> wrote:
> 
> > Added one sample to samples folder
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/DSC-SPIDAL/WebPViz/issues/9#issuecomment-153477972.
> 
> ## 
> 
> :
> : Geoffrey Fox gcf@indiana.edu Phones Cell 812-219-4643 Lab 8128567977
> http://www.infomall.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DSC-SPIDAL/WebPViz/issues/9#issuecomment-153480179.

## 

Supun Kamburugamuva
Member, Apache Software Foundation; http://www.apache.org
E-mail: supun06@gmail.com;  Mobile: +1 812 369 6762
Blog: http://supunk.blogspot.com

**Comment by supunkamburugamuve** [comment]
Added two files.
